// Generated by Wrangler on Wed Jul 31 2024 12:24:04 GMT+0200 (Central European Summer Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	__NEXT_ON_PAGES__KV_SUSPENSE_CACHE: KVNamespace;
}
